"""
scripts/setup_ssi_credentials.py
Thiết lập SSI credentials lần đầu — chạy 1 lần sau khi clone repo.

Encrypts credentials với machine-specific key và lưu vào .env.
File .env đã gitignore → an toàn, không push lên GitHub.

Usage:
    py -3.12 scripts/setup_ssi_credentials.py
"""

import sys
from pathlib import Path

# Add repo root to path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from analytics.secret_manager import encrypt_value, load_env, _ENV_PATH

# Load existing .env nếu có
load_env()

import os

# SSI credentials (đã được set trực tiếp bởi developer)
SSI_ACCOUNT  = "744037"
SSI_PASSWORD = "Vnpt@123456789"

print("Encrypting SSI credentials...")
acc_enc  = encrypt_value(SSI_ACCOUNT)
pass_enc = encrypt_value(SSI_PASSWORD)

env_content = f"""# SmartMoney Alpha Signal — Environment Config
# Generated by scripts/setup_ssi_credentials.py
# DO NOT COMMIT — file này đã gitignore (.env)

# ── SSI iBoard credentials (encrypted, machine-specific) ────────────────────
# Credentials được mã hóa bằng Fernet với key derive từ hostname+MAC address.
# Chỉ giải mã được trên máy đã chạy setup_ssi_credentials.py.
SSI_ACCOUNT_ENC={acc_enc}
SSI_PASSWORD_ENC={pass_enc}

# ── SSI API config ───────────────────────────────────────────────────────────
SSI_RATE_LIMIT_PER_MIN=20
SSI_TOKEN_TTL_HOURS=20

# ── Database paths (optional override) ──────────────────────────────────────
# DB_PATH=data/db/snapshots.db

# ── Feature flags ────────────────────────────────────────────────────────────
ENABLE_PROPRIETARY_DATA=true
"""

_ENV_PATH.write_text(env_content, encoding="utf-8")
print(f"✅ Đã lưu credentials vào: {_ENV_PATH}")
print("   (Encrypted, machine-specific — chỉ giải mã trên máy này)")

# Verify round-trip
from analytics.secret_manager import decrypt_value, get_ssi_credentials
load_env(_ENV_PATH)
# Re-load to pick up new values
for line in env_content.splitlines():
    if "=" in line and not line.startswith("#"):
        k, _, v = line.partition("=")
        os.environ[k.strip()] = v.strip()

acc_check, pass_check = get_ssi_credentials()
assert acc_check == SSI_ACCOUNT, "Account mismatch!"
assert pass_check == SSI_PASSWORD, "Password mismatch!"
print("✅ Kiểm tra giải mã thành công")
print(f"   Account: {acc_check[:3]}{'*'*len(acc_check[3:])}")
