"""
scripts/setup_ssi_credentials.py
Thiết lập SSI FastConnect API credentials — chạy 1 lần.

SSI Open API dùng consumerID + consumerSecret (KHÔNG phải username/password).
Lấy credentials tại:
  https://iboard.ssi.com.vn/support/api-service/management
  (Đăng nhập iBoard → Support → API Service Management)

Auth endpoint (đã verify): POST https://fc-data.ssi.com.vn/api/v2/Market/AccessToken

Usage:
    py -3.12 scripts/setup_ssi_credentials.py
    py -3.12 scripts/setup_ssi_credentials.py --consumer-id YOUR_ID --consumer-secret YOUR_SECRET
"""

import sys
import argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from analytics.secret_manager import encrypt_value, load_env, _ENV_PATH

load_env()
import os

# ── Parse args ──────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Setup SSI API credentials")
parser.add_argument("--consumer-id",     default="", help="SSI consumerID")
parser.add_argument("--consumer-secret", default="", help="SSI consumerSecret")
args = parser.parse_args()

SSI_CONSUMER_ID     = args.consumer_id     or os.getenv("SSI_CONSUMER_ID", "")
SSI_CONSUMER_SECRET = args.consumer_secret or os.getenv("SSI_CONSUMER_SECRET", "")

if not SSI_CONSUMER_ID or not SSI_CONSUMER_SECRET:
    print("\n⚠️  consumerID và consumerSecret chưa được cung cấp.")
    print("   Lấy tại: https://iboard.ssi.com.vn/support/api-service/management")
    print("\n   Cách chạy:")
    print('   py -3.12 scripts/setup_ssi_credentials.py --consumer-id YOUR_ID --consumer-secret YOUR_SECRET\n')
    sys.exit(1)

print(f"Encrypting SSI credentials (consumerID: {SSI_CONSUMER_ID[:4]}...)...")
id_enc  = encrypt_value(SSI_CONSUMER_ID)
sec_enc = encrypt_value(SSI_CONSUMER_SECRET)

env_content = f"""# SmartMoney Alpha Signal — Environment Config
# Generated by scripts/setup_ssi_credentials.py
# DO NOT COMMIT — file này đã gitignore (.env)

# ── SSI FastConnect API credentials (encrypted, machine-specific) ────────────
# Auth endpoint: POST https://fc-data.ssi.com.vn/api/v2/Market/AccessToken
# Lấy consumerID/consumerSecret tại:
#   https://iboard.ssi.com.vn/support/api-service/management
SSI_CONSUMER_ID_ENC={id_enc}
SSI_CONSUMER_SECRET_ENC={sec_enc}

# ── SSI API config ───────────────────────────────────────────────────────────
SSI_RATE_LIMIT_PER_MIN=20
SSI_TOKEN_TTL_HOURS=20

# ── Feature flags ────────────────────────────────────────────────────────────
ENABLE_PROPRIETARY_DATA=true
"""

_ENV_PATH.write_text(env_content, encoding="utf-8")
print(f"✅ Đã lưu credentials vào: {_ENV_PATH}")
print("   (Encrypted với machine-specific key — chỉ giải mã trên máy này)")

# Verify round-trip
from analytics.secret_manager import get_ssi_credentials
for line in env_content.splitlines():
    if "=" in line and not line.startswith("#"):
        k, _, v = line.partition("=")
        os.environ[k.strip()] = v.strip()

id_check, sec_check = get_ssi_credentials()
assert id_check  == SSI_CONSUMER_ID,     "consumerID mismatch!"
assert sec_check == SSI_CONSUMER_SECRET, "consumerSecret mismatch!"
print("✅ Kiểm tra giải mã thành công")
print(f"   consumerID: {id_check[:4]}{'*'*max(0, len(id_check)-4)}")
